### ISSUE TITLE
Atom lists 0.2.0 as the latest version?

### ISSUE THREAD

**Issue by jason-o-matic** [redbassett/wraptor#12]
I noticed https://atom.io/packages/wraptor lists 0.2.0 as the version (as does the Atom package install interface). It looks like the 0.2.0 release on GitHub was a while ago. Was the 0.2.0 release unintentional, and are people who install the package normally getting an old version?

**Comment by redbassett** [comment]
I noticed this too, but I've got a `0.2.0` tag, but I didn't intentionally publish it, and I don't see it in commit history, I think it may have been pushed by `apm` and then written over. I may check with the Atom folks about fixing it, or I may release again as `0.2.1`. Not sure yet, but input is welcome!

**Comment by jason-o-matic** [comment]
I think git tags are generally supposed to be "forever" so I'd hesitate to delete it. I'd probably just release again as `0.2.1`. Also it's easy and doesn't involve communication delay.

That's just my leaning, though. Either way seems like a reasonable plan.

**Comment by redbassett** [comment]
I'd take that as reason enough to just issue a new tag. I'll push something out later.

**Comment by redbassett** [comment]
A little messy getting APM to accept the update, but `0.2.1` has been pushed as of f7d4d40cf2bc217459b37985c9d77f1307b96cfe.
